spring.application.name=Angualr-Springboot

# MySQL database connection properties
spring.datasource.url=jdbc:mysql://localhost:3307/employee_management
spring.datasource.username=${MYDBUSER}
spring.datasource.password=${MYDBPASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate properties (optional but recommended for data access)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

